title: Amrutha Purna Vadrevu
logo: https://github.com/amruthapurnavadrevu/amruthapurnavadrevu.github.io/blob/main/Images/Profile.jpeg
description: MSc Data Science, Heriot-Watt University, United Kingdom
theme: jekyll-theme-minimal
